replicaCount: 2
image:
  repository: frontend
  tag: latest
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
ingress:
  enabled: true
  hosts:
    - host: ecommerce.local
      paths:
        - path: /
          pathType: Prefix
